import Login from '@/components/Login';
import Head from 'next/head';
import Nav from '@/components/Nav';
import Timesheet from '@/components/Timesheet';

export default function Home() {
  return (
    <>
      <Head>
        <title>RocketTime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Timesheet />
      </main>
    </>
  )
}
